apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: staging
  namespace: argocd
spec:
  description: IMU Staging Project
  sourceRepos:
    - https://github.com/your-org/imu_repo
    - https://prometheus-community.github.io/helm-charts
    - https://open-policy-agent.github.io/gatekeeper/charts
  destinations:
    - namespace: staging
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"