apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cp.fullname" . }}-api
  namespace: {{ .Values.namespace }}
  labels: { app: {{ include "cp.fullname" . }}, tier: api }
spec:
  replicas: {{ .Values.replicas.api }}
  selector:
    matchLabels: { app: {{ include "cp.fullname" . }}, tier: api }
  template:
    metadata:
      labels: { app: {{ include "cp.fullname" . }}, tier: api }
    spec:
      {{- if .Values.availability.spread.enabled }}
      topologySpreadConstraints:
        - maxSkew: {{ .Values.availability.spread.maxSkew }}
          topologyKey: {{ .Values.availability.spread.topologyKey | quote }}
          whenUnsatisfiable: {{ .Values.availability.spread.whenUnsatisfiable | quote }}
          labelSelector:
            matchLabels: { app: {{ include "cp.fullname" . }}, tier: api }
      {{- end }}    
      replicas: {{ .Values.replicas.api }}
      selector: { matchLabels: { app: {{ include "cp.fullname" . }}, tier: api } }
      template:
        metadata: { labels: { app: {{ include "cp.fullname" . }}, tier: api } }
        spec:
          serviceAccountName: {{ include "cp.fullname" . }}-sa
          securityContext: {{- toYaml .Values.securityContext.pod | nindent 6 }}
          containers:
          - name: api
            image: "{{ .Values.images.api.repository }}:{{ .Values.images.api.tag }}"
            imagePullPolicy: "{{ .Values.images.api.pullPolicy }}"
            securityContext: {{- toYaml .Values.securityContext.container | nindent 8 }}
            ports: [ { containerPort: {{ .Values.service.apiPort }} } ]
        # מצופה שה-image יפעיל: uvicorn server.http_api:APP --host 0.0.0.0 --port 8000
