apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cp.fullname" . }}-ui
  namespace: {{ .Values.namespace }}
  labels: { app: {{ include "cp.fullname" . }}, tier: ui }
spec:
  replicas: {{ .Values.replicas.ui }}
  selector:
    matchLabels: { app: {{ include "cp.fullname" . }}, tier: ui }
  template:
    metadata:
      labels: { app: {{ include "cp.fullname" . }}, tier: ui }
    spec:
      containers:
      - name: ui
        image: "{{ .Values.images.ui.repository }}:{{ .Values.images.ui.tag }}"
        imagePullPolicy: "{{ .Values.images.ui.pullPolicy }}"
        ports:
        - containerPort: {{ .Values.service.uiPort }}
        volumeMounts:
        - name: ui-html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: ui-html
        configMap:
          name: {{ include "cp.fullname" . }}-ui