{{- if .Values.synthetics.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cp.fullname" . }}-k6
  namespace: {{ .Values.namespace }}
data:
  k6.js: |
    import http from 'k6/http';
    import ws   from 'k6/ws';
    import { check, sleep } from 'k6';

    export let options = {
      scenarios: {
        ws_timeline: { executor: 'constant-vus', vus: 2, duration: __ENV.DURATION || '20s' }
      }
    };

    export default function () {
      const apiBase = __ENV.API_BASE;
      const wsUrl   = __ENV.WS_URL || "";
      if (!apiBase || !wsUrl) return;

      let received = 0;
      const res = ws.connect(wsUrl, {}, function (socket) {
        socket.on('open', function(){
          // שלח 3 אירועים דרך API, אמורים להגיע ל־WS
          for (let i=0;i<3;i++){
            http.post(`${apiBase}/events/publish`, JSON.stringify({topic:"timeline",producer:"k6",priority:5,event:{type:"event",note:`k6-echo-${i}`}}), { headers:{'content-type':'application/json'} });
            sleep(0.5);
          }
        });
        socket.on('message', function(d){
          try {
            const o = JSON.parse(d);
            if (o && o.producer==="k6" && String(o.note||"").startsWith("k6-echo-")) {
              received++;
            }
          } catch(e){}
        });
        socket.setTimeout(function(){ socket.close(); }, 5000);
      });
      check(res, { 'ws 101': (r)=>r && r.status===101 });
      check(received, { 'got at least 3 echoes': (v)=> v>=3 });
    }
{{- end }}