{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cp.fullname" . }}-np
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "cp.fullname" . }}
  policyTypes: [Ingress, Egress]
  ingress:
  - {}
  {{- if eq .Values.networkPolicy.profile "strict" }}
  - from:
    {{- if .Values.networkPolicy.allowSameNamespace }}
    - podSelector: {}
    {{- end }}
    {{- range .Values.networkPolicy.ingressCidrs }}
    - ipBlock: { cidr: {{ . }} }
    {{- end }}
  {{- else if eq .Values.networkPolicy.profile "standard" }}
  - from: [ { podSelector: {} } ]
  {{- else }}
  - {}
  {{- end }}
  egress:
  - {}
  {{- if eq .Values.networkPolicy.profile "strict" }}
  - to:
    {{- range .Values.networkPolicy.egressCidrs }}
    - ipBlock: { cidr: {{ . }} }
    {{- end }}
  {{- else if eq .Values.networkPolicy.profile "standard" }}
  - {}
  {{- else }}
  - {}
  {{- end }}
{{- end }}