alertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 2m
    route:
      group_by: ['alertname','job','release']
      group_wait: 10s
      group_interval: 2m
      repeat_interval: 2h
      receiver: 'null'
      routes:
        - matchers: [ severity="warning" ]
          receiver: 'slack'
        - matchers: [ severity="critical" ]
          receiver: 'slack'
        - matchers: [ team="platform" ]
          receiver: 'teams'
        - matchers: [ team="oncall" ]
          receiver: 'email'
    receivers:
      - name: 'null'
      - name: 'slack'
        slack_configs:
          - send_resolved: true
            api_url: '{{ .Values.alerts.slack.webhook | default "" }}'
            channel: '{{ .Values.alerts.slack.channel | default "#platform-alerts" }}'
            title: '{{ template "slack.title" . }}'
            text:  '{{ template "slack.text"  . }}'
      - name: 'teams'
        webhook_configs:
          - url: '{{ .Values.alerts.teams.webhook | default "" }}'
            http_config: {}
            send_resolved: true
            max_alerts: 0
            # card JSON מגודל מתוך התבנית
            template: '/etc/alertmanager/config/teams.tmpl'
      - name: 'email'
        email_configs:
          - to:   '{{ .Values.alerts.email.to   | default "" }}'
            from: '{{ .Values.alerts.email.from | default "" }}'
            smarthost: '{{ .Values.alerts.email.smarthost | default "" }}'
            auth_username: '{{ .Values.alerts.email.authUsername | default "" }}'
            auth_password: '{{ .Values.alerts.email.authPassword | default "" }}'
            headers:
              subject: '[IMU] {{ (index .Alerts 0).Labels.severity | toUpper }} {{ (index .Alerts 0).Labels.alertname }}'
            html: '{{ template "email.html" . }}'
    templates:
      - '/etc/alertmanager/config/*.tmpl'

alerts:
  slack:
    webhook: ""                  # ⚠️ נדרש אם Slack בשימוש (gating)
    channel: "#platform-alerts"
  teams:
    webhook: ""                  # ⚠️ נדרש אם Teams בשימוש (gating)
  email:
    to: "oncall@example.com"     # ⚠️ נדרש אם Email בשימוש (gating)
    from: "alerts@example.com"
    smarthost: "smtp.example.com:587"
    authUsername: ""
    authPassword: ""

# Gate: כש־receivers פעילים — חייבים ערכים לא ריקים
gating:
  alerts:
    requireSlackWebhook: true
    requireTeamsWebhook: true
    requireEmailFields: true
helm/umbrella/templates/alertmanager-configmap-templates.yaml (מלא)
{{- if and .Values.alertmanager.enabled .Values.alertmanager.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-am-templates
  namespace: {{ .Values.namespace | default "default" }}
data:
  slack.tmpl: |
    {{ define "slack.title" -}}
    [{{ (index .Alerts 0).Labels.severity | toUpper }}] {{ (index .Alerts 0).Labels.alertname }}
    {{- end }}
    {{ define "slack.text" -}}
    *Summary:* {{ (index .Alerts 0).Annotations.summary | default "n/a" }}
    *Desc:* {{ (index .Alerts 0).Annotations.description | default "n/a" }}
    *Namespace:* {{ (index .Alerts 0).Labels.namespace | default "n/a" }}
    *Release:* {{ .Release.Name }}
    *Grafana:* {{ .ExternalURL | default "https://grafana.example.com" }}
    {{- end }}

  teams.tmpl: |
    {{ define "teams.card" -}}
    {
      "@type":"MessageCard","@context":"https://schema.org/extensions",
      "themeColor":"0076D7",
      "summary":"{{ (index .Alerts 0).Annotations.summary | default "IMU Alert" }}",
      "sections":[
        {"activityTitle":"[{{ (index .Alerts 0).Labels.severity | toUpper }}] {{ (index .Alerts 0).Labels.alertname }}",
         "facts":[
           {"name":"Namespace","value":"{{ (index .Alerts 0).Labels.namespace | default "n/a" }}"},
           {"name":"Description","value":"{{ (index .Alerts 0).Annotations.description | default "n/a" }}"},
           {"name":"Release","value":"{{ .Release.Name }}"},
           {"name":"Grafana","value":"{{ .ExternalURL | default "https://grafana.example.com" }}"}
         ],
         "markdown":true}
      ]
    }
    {{- end }}

  email.tmpl: |
    {{ define "email.html" -}}
    <h2>[{{ (index .Alerts 0).Labels.severity | toUpper }}] {{ (index .Alerts 0).Labels.alertname }}</h2>
    <p><b>Summary:</b> {{ (index .Alerts 0).Annotations.summary | default "n/a" }}</p>
    <p><b>Description:</b> {{ (index .Alerts 0).Annotations.description | default "n/a" }}</p>
    <p><b>Namespace:</b> {{ (index .Alerts 0).Labels.namespace | default "n/a" }}</p>
    <p><b>Release:</b> {{ .Release.Name }}</p>
    <p><b>Grafana:</b> {{ .ExternalURL | default "https://grafana.example.com" }}</p>
    {{- end }}
{{- end }}