{{- if .Values.synthetics.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "cp.fullname" . }}-postsync-k6
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: {{ include "cp.fullname" . }}-sa
      restartPolicy: Never
      containers:
      - name: k6
        image: grafana/k6:0.49.0
        env:
        - { name: DURATION, value: "{{ .Values.synthetics.duration }}" }
        - name: API_BASE
          value: "http://{{ include "cp.fullname" . }}-svc.{{ .Values.namespace }}.svc.cluster.local:{{ .Values.service.apiPort }}"
        - name: WS_URL
          value: "{{ .Values.synthetics.ws.url }}"
        command: [ "sh", "-c" ]
        args:
          - |
            echo "[k6] ws publish/receive test ...";
            set -e
            k6 run /cfg/k6.js || FAILED=1
            if [ "${FAILED:-0}" = "1" ]; then
              echo "[k6] FAILED – rollback";
              helm rollback "{{ .Release.Name }}" 1 -n "{{ .Values.namespace }}" || true
              exit 1
            fi
      volumes:
      - name: cfg
        configMap: { name: {{ include "cp.fullname" . }}-k6 }
{{- end }}