version: "3.9"

services:
  ws:
    build:
      context: .
      dockerfile: docker/ws/Dockerfile
    command: python -m server.stream_wfq_ws
    ports:
      - "${WS_PORT:-8766}:8766"
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s=socket.socket(); s.connect(('127.0.0.1',8766)); s.close()"]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: docker/prod/api/Dockerfile
    env_file: [ .env ]
    environment:
      WS_URL: ${WS_URL:-ws://ws:8766}
      PYTHONPATH: ${PYTHONPATH:-/app}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    depends_on:
      ws:
        condition: service_healthy
    ports:
      - "${API_PORT:-8000}:8000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8000/readyz"]
      interval: 10s
      timeout: 3s
      retries: 12
    restart: unless-stopped

  ui:
    build:
      context: .
      dockerfile: docker/ui/Dockerfile
    ports:
      - "${UI_PORT:-8080}:80"
    restart: unless-stopped

networks:
  default:
    name: imu_net
