apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: imu-gatekeeper
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://open-policy-agent.github.io/gatekeeper/charts
    chart: gatekeeper
    targetRevision: 3.16.0
    helm:
      values: |
        auditInterval: 30
        enableDeleteOperations: true
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
  syncPolicy:
    automated: { prune: true, selfHeal: true }