kube-prometheus-stack:
  grafana:
    grafana.ini:
      server:
        root_url: https://grafana.yourcompany.com
      auth:
        disable_login_form: true
        disable_signout_menu: false
      auth.generic_oauth:
        enabled: true
        name: "SSO"
        allow_sign_up: true
        scopes: "openid profile email"
        auth_url: "https://idp.example.com/oauth2/v1/authorize"
        token_url: "https://idp.example.com/oauth2/v1/token"
        api_url: "https://idp.example.com/oauth2/v1/userinfo"
        client_id:  "${GRAFANA_OIDC_CLIENT_ID}"
        client_secret: "${GRAFANA_OIDC_CLIENT_SECRET}"
    envValueFrom:
      GRAFANA_OIDC_CLIENT_ID:
        secretKeyRef:
          name: grafana-oidc
          key: client_id
      GRAFANA_OIDC_CLIENT_SECRET:
        secretKeyRef:
          name: grafana-oidc
          key: client_secret