apiVersion: v2
name: imu-control-plane
description: IMU Control Plane (API + WFQ WebSocket + Static UI)
type: application
version: 0.1.0
appVersion: "1.0.0"
helm/control-plane/values.yaml
namespace: default

images:
  api:
    repository: ghcr.io/your-org/imu-api
    tag: latest
    pullPolicy: IfNotPresent
  ws:
    repository: ghcr.io/your-org/imu-ws
    tag: latest
    pullPolicy: IfNotPresent
  ui:
    repository: nginx
    tag: alpine
    pullPolicy: IfNotPresent

replicas:
  api: 1
  ws: 1
  ui: 1

service:
  apiPort: 8000
  wsPort: 8766
  uiPort: 8080
  type: ClusterIP

ingress:
  enabled: false
  className: ""
  hosts:
    - host: imu.local
      paths:
        - path: /
          service: ui
          port: 8080
        - path: /ws
          service: ws
          port: 8766
        - path: /api
          service: api
          port: 8000
  tls: []