{{- if and .Values.gatekeeper.enabled .Values.gatekeeper.requireLabels.enabled }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabel
metadata:
  name: require-team-label
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters:
    labels: [ "{{ .Values.gatekeeper.requireLabels.key }}" ]
{{- end }}