{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cp.fullname" . }}-ing
  namespace: {{ .Values.namespace }}
  {{- if .Values.ingress.className }}
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingress.className }}"
  {{- end }}
spec:
  rules:
{{- range .Values.ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "cp.fullname" $ }}-svc
            port:
              number: {{ .port }}
      {{- end }}
{{- end }}
  tls:
{{ toYaml .Values.ingress.tls | indent 2 }}
{{- end }}