{{- if .Values.rbac.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cp.fullname" . }}-sa
  namespace: {{ .Values.namespace }}
{{- end }}
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cp.fullname" . }}-role
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [""]
  resources: ["configmaps","secrets","pods","pods/log","services"]
  verbs: ["get","list","watch","create","update","patch","delete"]
- apiGroups: ["apps"]
  resources: ["deployments","replicasets","statefulsets"]
  verbs: ["get","list","watch","create","update","patch","delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get","list","watch","create","update","patch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cp.fullname" . }}-rb
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "cp.fullname" . }}-sa
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "cp.fullname" . }}-role
{{- end }}
