site_name: IMU Platform
site_url: https://your-org.github.io/imu_repo
theme:
  name: material
  features: [ navigation.instant, content.code.copy ]
nav:
  - Overview: index.md
  - Runbooks:
      - Deploy Control Plane: runbooks/deploy.md
      - Emergency Rollback: runbooks/emergency.md
  - Diagrams:
      - Architecture: diagrams/architecture.md
      - Umbrella (auto): diagrams/generated/umbrella.md
  - Governance & SLO: governance/slo.md
markdown_extensions:
  - admonition
  - codehilite
  - toc: { permalink: true }
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js
extra_css: []