lertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 2m

    time_intervals:
      - name: business-hours
        time_intervals:
          - weekdays: ['monday:friday']
            times:
              - start_time: '09:00'
                end_time:   '18:00'
      - name: off-hours
        time_intervals:
          - weekdays: ['monday:friday']
            times:
              - start_time: '18:00'
                end_time:   '24:00'
          - weekdays: ['saturday:sunday']

    route:
      group_by: [ 'alertname','job','release' ]
      group_wait: 15s
      group_interval: 2m
      repeat_interval: 2h
      receiver: 'null'
      routes:
        # business-hours: Slack only
        - matchers: [ severity="warning" ]
          receiver: 'slack'
          active_time_intervals: [ 'business-hours' ]

        # off-hours: Slack + Pager (Teams/email) אסקלציה אחרי 10 דק
        - matchers: [ severity="warning" ]
          receiver: 'slack'
          active_time_intervals: [ 'off-hours' ]
          continue: true
        - matchers: [ severity="warning" ]
          receiver: 'pager'
          active_time_intervals: [ 'off-hours' ]
          repeat_interval: 10m

        # critical — תמיד גם Pager
        - matchers: [ severity="critical" ]
          receiver: 'slack'
          continue: true
        - matchers: [ severity="critical" ]
          receiver: 'pager'

    receivers:
      - name: 'null'

      - name: 'slack'
        slack_configs:
          - send_resolved: true
            api_url: '{{ .Values.alerts.slack.webhook | default "" }}'
            channel: '{{ .Values.alerts.slack.channel | default "#platform-alerts" }}'
            title: '{{ template "slack.title" . }}'
            text:  '{{ template "slack.text"  . }}'

      - name: 'pager'
        webhook_configs:
          - url: '{{ .Values.alerts.teams.webhook | default "" }}'
            send_resolved: true
        email_configs:
          - to:   '{{ .Values.alerts.email.to   | default "" }}'
            from: '{{ .Values.alerts.email.from | default "" }}'
            smarthost: '{{ .Values.alerts.email.smarthost | default "" }}'
            headers:
              subject: '[IMU {{ (index .Alerts 0).Labels.severity | toUpper }}] {{ (index .Alerts 0).Labels.alertname }}'
            html: '{{ template "email.html" . }}'

    templates:
      - '/etc/alertmanager/config/*.tmpl'

alerts:
  slack: { webhook: "", channel: "#platform-alerts" }
  teams: { webhook: "" }               # Pager (Teams)
  email:
    to: "oncall@example.com"
    from: "alerts@example.com"
    smarthost: "smtp.example.com:587"
    authUsername: ""
    authPassword: ""

gating:
  alerts:
    requireSlackWebhook: true
    requireTeamsWebhook: true
    requireEmailFields:  true