namespace: default

controlPlane:
  enabled: true
  imu-control-plane:
    namespace: "{{ .Values.namespace }}"
    dashboards: { enabled: true }

monitoring:
  enabled: true

gatekeeper:
  enabled: true

ingressNginx:
  enabled: true
  controller:
    service:
      type: LoadBalancer

certManager:
  enabled: true
  installCRDs: true
  email: "acme@example.com"          # נדרש ע"י gating אם ACME מופעל
  acme:
    enabled: true                    # אם true — נדרוש email לא ריק
    server: "https://acme-v02.api.letsencrypt.org/directory"
    solver: http01                   # או dns01 (ואז נדרוש גם dns provider)
    dns01:
      provider: ""                   # אם dns01 — נדרוש provider לא ריק

externalDNS:
  enabled: true
  provider: "cloudflare"             # או aws / google / azure / rfc2136
  domainFilters: [ "yourcompany.com" ]
  txtOwnerId: "imu"
  policy: "sync"
  serviceAccount:
    create: true
    name: ""

# --- Policy Gating (כאן מגדירים מה מותר) ---
gating:
  enabled: true
  allowedIngressClasses: [ "nginx" ]
  allowedDNSZones: [ "yourcompany.com" ]
  requireTLSForIngress: true
  requireCertManagerEmail: true
  requireExternalDNSProviderIn: [ "cloudflare", "aws", "google", "azure", "rfc2136" ]
  requireExternalDNSForIngress: true

loki:
  enabled: false
  lokiStack:
    grafana: { enabled: false }
    promtail:
      enabled: true
      config:
        clients:
          - url: http://loki:3100/loki/api/v1/push