# Global namespace reference (can be overridden per env)
namespace: default

controlPlane:
  enabled: true
  # Pass-through values to the subchart (control-plane)
  imu-control-plane:
    namespace: "{{ .Values.namespace }}"
    dashboards:
      enabled: true
    hpa:
      enabled: true
      api: { min: 1, max: 5, cpu: 75 }
      ws:  { min: 1, max: 5, cpu: 75 }
    networkPolicy:
      enabled: true
      profile: standard

monitoring:
  enabled: true
  kube-prometheus-stack:
    grafana:
      sidecar:
        dashboards:
          enabled: true
          label: grafana_dashboard
          searchNamespace: ALL
      defaultDashboardsEnabled: false
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false

gatekeeper:
  enabled: true
  gatekeeper:
    auditInterval: 30
    enableDeleteOperations: true