{{- if .Values.gating.enabled }}
{{/* Fail early: Ingress TLS gating */}}
{{- if and .Values.controlPlane.enabled (eq .Values.controlPlane.imu-control-plane.ingress.enabled true) }}
  {{- if and .Values.gating.requireTLSForIngress (not .Values.controlPlane.imu-control-plane.ingress.tls) }}
    {{- fail "Gating: control-plane ingress enabled but TLS not configured (set controlPlane.imu-control-plane.ingress.tls)" }}
  {{- end }}
  {{- $cls := (default "" .Values.controlPlane.imu-control-plane.ingress.className) -}}
  {{- if and $cls (not (has $cls .Values.gating.allowedIngressClasses)) }}
    {{- fail (printf "Gating: ingress class '%s' not in allowedIngressClasses" $cls) }}
  {{- end }}
{{- end }}

{{/* External DNS provider + domain allowlist */}}
{{- if .Values.externalDNS.enabled }}
  {{- $prov := (default "" .Values.externalDNS.provider) -}}
  {{- if not (has $prov .Values.gating.requireExternalDNSProviderIn) }}
    {{- fail (printf "Gating: externalDNS.provider '%s' not allowed" $prov) }}
  {{- end }}
  {{- if (empty .Values.externalDNS.domainFilters) }}
    {{- fail "Gating: externalDNS.domainFilters must not be empty" }}
  {{- end }}
  {{- $bad := list -}}
  {{- range .Values.externalDNS.domainFilters }}
    {{- if not (has . $.Values.gating.allowedDNSZones) }}
      {{- $bad = append $bad . -}}
    {{- end }}
  {{- end }}
  {{- if gt (len $bad) 0 }}
    {{- fail (printf "Gating: externalDNS.domainFilters contain disallowed zones: %v" $bad) }}
  {{- end }}
{{- end }}

{{/* cert-manager ACME: require email if enabled */}}
{{- if and .Values.certManager.enabled .Values.certManager.acme.enabled }}
  {{- if and .Values.gating.requireCertManagerEmail (empty .Values.certManager.email) }}
    {{- fail "Gating: certManager.acme.enabled=true requires non-empty certManager.email" }}
  {{- end }}
{{- end }}
{{/* Ingress enabled but ExternalDNS disabled ⇒ fail */}}
{{- if and .Values.controlPlane.enabled (eq .Values.controlPlane.imu-control-plane.ingress.enabled true) }}
  {{- if and .Values.gating.requireExternalDNSForIngress (not .Values.externalDNS.enabled) }}
    {{- fail "Gating: ingress enabled but externalDNS is disabled (set externalDNS.enabled=true)" }}
  {{- end }}
{{- end }}
{{- end }}