
apiVersion: v1
kind: Secret
metadata:
  name: argocd-oidc
  namespace: argocd
type: Opaque
stringData:
  client_id: placeholder    # יוחלף ע"י ESO/Pulumi – אין להשאיר כך בפרודקשן #TODO 
  client_secret: placeholder