{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "cp.fullname" . }}-api-hpa
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef: { apiVersion: apps/v1, kind: Deployment, name: {{ include "cp.fullname" . }}-api }
  minReplicas: {{ .Values.hpa.api.min }}
  maxReplicas: {{ .Values.hpa.api.max }}
  metrics: [ { type: Resource, resource: { name: cpu, target: { type: Utilization, averageUtilization: {{ .Values.hpa.api.cpu }} } } } ]
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "cp.fullname" . }}-ws-hpa
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef: { apiVersion: apps/v1, kind: Deployment, name: {{ include "cp.fullname" . }}-ws }
  minReplicas: {{ .Values.hpa.ws.min }}
  maxReplicas: {{ .Values.hpa.ws.max }}
  metrics: [ { type: Resource, resource: { name: cpu, target: { type: Utilization, averageUtilization: {{ .Values.hpa.ws.cpu }} } } } ]
{{- end }}