{{- if .Values.availability.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cp.fullname" . }}-api-pdb
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: {{ .Values.availability.pdb.api.minAvailable }}
  selector: { matchLabels: { app: {{ include "cp.fullname" . }}, tier: api } }
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cp.fullname" . }}-ws-pdb
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: {{ .Values.availability.pdb.ws.minAvailable }}
  selector: { matchLabels: { app: {{ include "cp.fullname" . }}, tier: ws } }
{{- end }}