apiVersion: v1
kind: Service
metadata:
  name: {{ include "cp.fullname" . }}-svc
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector: { app: {{ include "cp.fullname" . }} }
  ports:
  - name: api
    port: {{ .Values.service.apiPort }}
    targetPort: {{ .Values.service.apiPort }}
  - name: ws
    port: {{ .Values.service.wsPort }}
    targetPort: {{ .Values.service.wsPort }}
  - name: ui
    port: {{ .Values.service.uiPort }}
    targetPort: {{ .Values.service.uiPort }}