apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "cp.fullname" . }}-alerts
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "cp.fullname" . }}
spec:
  groups:
  - name: imu-slo-alerts
    rules:
    - alert: IMUKindSmokeFailed
      expr: last_over_time(imu_kind_smoke_pass[30m]) == 0
      for: 5m
      labels: { severity: warning, team: platform }
      annotations:
        summary: "Kind smoke failed (last run)"
        description: "imu_kind_smoke_pass == 0 in the last 30 minutes"

    - alert: IMUHelmTestFailed
      expr: last_over_time(imu_helm_test_pass[30m]) == 0
      for: 5m
      labels: { severity: warning, team: platform }
      annotations:
        summary: "Helm tests failing"
        description: "imu_helm_test_pass == 0 in the last 30 minutes"

    - alert: IMUUnexpectedDiffs
      expr: max_over_time(imu_allowed_diffs_unexpected_total[1h]) > 0
      for: 10m
      labels: { severity: info, team: platform }
      annotations:
        summary: "Unexpected diffs detected by CI"
        description: "imu_allowed_diffs_unexpected_total > 0 over last hour"