{{- if and .Values.gating.enabled .Values.externalSecrets.enabled }}
{{- $ns := .Values.secrets.namespace | default .Values.namespace | default "default" -}}
{{- $need := list "alerts-slack" "alerts-teams" "alerts-email" "alerts-pagerduty" "alerts-opsgenie" -}}
{{- range $need }}
  {{- $s := (lookup "v1" "Secret" $ns .) -}}
  {{- if not $s }}
    {{- fail (printf "Gating: required Secret '%s/%s' not found (ExternalSecret not ready?)" $ns .) }}
  {{- end }}
{{- end }}
{{- end }}