name: build-and-push
on:
  push:
    branches: [ "main" ]
    paths:
      - 'docker/**'
      - 'server/**'
      - 'adapters/**'
      - 'ui/**'
      - 'requirements.txt'
  workflow_dispatch: {}

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build API
        run: |
          docker build -t $REGISTRY/$IMAGE_OWNER/imu-api:latest -f docker/api/Dockerfile .
          docker push $REGISTRY/$IMAGE_OWNER/imu-api:latest
      - name: Build WS
        run: |
          docker build -t $REGISTRY/$IMAGE_OWNER/imu-ws:latest -f docker/ws/Dockerfile .
          docker push $REGISTRY/$IMAGE_OWNER/imu-ws:latest
      - name: Build UI
        run: |
          docker build -t $REGISTRY/$IMAGE_OWNER/imu-ui:latest -f docker/ui/Dockerfile .
          docker push $REGISTRY/$IMAGE_OWNER/imu-ui:latest