name: mermaid-diagrams
on:
  push:
    branches: [ "main" ]
    paths: [ "helm/umbrella/*.yaml", "scripts/gen_mermaid_from_values.py", "docs/**", "mkdocs.yml" ]
  workflow_dispatch: {}

jobs:
  gen-diagrams:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install pyyaml
      - run: |
          chmod +x scripts/gen_mermaid_from_values.py
          scripts/gen_mermaid_from_values.py \
            --values helm/umbrella/values.yaml helm/umbrella/values.dev.yaml \
            --out docs/diagrams/generated/umbrella.md
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: update mermaid diagram"
          file_pattern: docs/diagrams/generated/umbrella.md