{{- if and .Values.alertmanager.enabled .Values.alertmanager.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-am-templates
  namespace: {{ .Values.namespace | default "default" }}
data:
  slack.tmpl: |
    {{- $url := .Values.dashboards.grafanaUrl | default "https://grafana.example.com" -}}
    {{- $slo := printf "%s/d/%s?from=now-6h&to=now" $url (.Values.dashboards.sloUid | default "imu_slo") -}}
    {{- $gate := printf "%s/d/%s?from=now-6h&to=now" $url (.Values.dashboards.gateUid | default "imu_gatekeeper") -}}
    {{ define "slack.title" -}}
    [{{ (index .Alerts 0).Labels.severity | toUpper }}] {{ (index .Alerts 0).Labels.alertname }}
    {{- end }}
    {{ define "slack.text" -}}
    *Summary:* {{ (index .Alerts 0).Annotations.summary | default "n/a" }}
    *Desc:* {{ (index .Alerts 0).Annotations.description | default "n/a" }}
    *Namespace:* {{ (index .Alerts 0).Labels.namespace | default "n/a" }}
    *Release:* {{ .Release.Name }}
    *SLO:* <{{ $slo }}|open> • *Gate:* <{{ $gate }}|open>
    {{- end }}

  teams.tmpl: |
    {{- $url := .Values.dashboards.grafanaUrl | default "https://grafana.example.com" -}}
    {{- $slo := printf "%s/d/%s?from=now-6h&to=now" $url (.Values.dashboards.sloUid | default "imu_slo") -}}
    {{- $gate := printf "%s/d/%s?from=now-6h&to=now" $url (.Values.dashboards.gateUid | default "imu_gatekeeper") -}}
    {{ define "teams.card" -}}
    {
      "@type":"MessageCard","@context":"https://schema.org/extensions","themeColor":"0076D7",
      "summary":"{{ (index .Alerts 0).Annotations.summary | default "IMU Alert" }}",
      "sections":[
        {"activityTitle":"[{{ (index .Alerts 0).Labels.severity | toUpper }}] {{ (index .Alerts 0).Labels.alertname }}",
         "facts":[
           {"name":"Namespace","value":"{{ (index .Alerts 0).Labels.namespace | default "n/a" }}"},
           {"name":"Release","value":"{{ .Release.Name }}"},
           {"name":"SLO","value":"{{ $slo }}"},
           {"name":"Gate","value":"{{ $gate }}"}
         ],"markdown":true}
      ]
    }
    {{- end }}

  email.tmpl: |
    {{- $url := .Values.dashboards.grafanaUrl | default "https://grafana.example.com" -}}
    {{- $slo := printf "%s/d/%s?from=now-6h&to=now" $url (.Values.dashboards.sloUid | default "imu_slo") -}}
    {{- $gate := printf "%s/d/%s?from=now-6h&to=now" $url (.Values.dashboards.gateUid | default "imu_gatekeeper") -}}
    {{ define "email.html" -}}
    <h2>[{{ (index .Alerts 0).Labels.severity | toUpper }}] {{ (index .Alerts 0).Labels.alertname }}</h2>
    <p><b>Summary:</b> {{ (index .Alerts 0).Annotations.summary | default "n/a" }}</p>
    <p><b>Namespace:</b> {{ (index .Alerts 0).Labels.namespace | default "n/a" }}</p>
    <p><b>Release:</b> {{ .Release.Name }}</p>
    <p><b>SLO:</b> <a href="{{ $slo }}">open</a> • <b>Gate:</b> <a href="{{ $gate }}">open</a></p>
    {{- end }}
{{- end }}