{{- if .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.secrets.namespace | default .Values.namespace | default "default" }}
---
{{- range $i, $item := .Values.secrets.items }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $item.name }}
  namespace: {{ $.Values.secrets.namespace | default $.Values.namespace | default "default" }}
spec:
  refreshInterval: 1h
  secretStoreRef: { name: imu-secrets-store, kind: ClusterSecretStore }
  target:
    name: {{ $item.name }}
    creationPolicy: Owner
    template:
{{ toYaml $item.template | indent 6 }}
  data:
    - secretKey: {{ default "value" $item.property | empty | ternary "value" $item.property }}
      remoteRef:
        key: {{ $item.remoteKey | quote }}
        {{- if $item.property }}
        property: {{ $item.property | quote }}
        {{- end }}
---
{{- end }}
{{- end }}