{{- if and .Values.externalSecrets.enabled (eq (.Values.secrets.provider | default "aws") "aws") }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dex-oidc
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef: { name: imu-secrets-store, kind: ClusterSecretStore }
  target:
    name: dex-oidc
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef: { key: "/imu/prod/argocd/dex", property: "client_id" }
    - secretKey: client_secret
      remoteRef: { key: "/imu/prod/argocd/dex", property: "client_secret" }
{{- end }}