pipeline:
  - name: unity_cli
    config:
      project_path: /path/to/unity/project
      build_target: WebGL
      output_path: /tmp/build/webgl
  - name: k8s_deploy
    config:
      manifests_dir: /path/to/k8s/manifests
      namespace: games
      selector: app=unity-web
ui:
  streams:
    - kind: progress
      topic: progress
    - kind: timeline
      topic: timeline