name: cd-images-stable
on:
  push:
    branches: [ "main" ]
    paths:
      - 'docker/**'
      - 'server/**'
      - 'adapters/**'
      - 'ui/**'
      - 'requirements.txt'
  workflow_dispatch: {}

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute tag
        id: meta
        run: |
          SHA=${GITHUB_SHA::7}
          TS=$(date +%Y%m%d%H%M)
          echo "tag=stable-${TS}-${SHA}" >> $GITHUB_OUTPUT

      - name: Build API
        run: |
          docker build -t $REGISTRY/$IMAGE_OWNER/imu-api:${{ steps.meta.outputs.tag }} -t $REGISTRY/$IMAGE_OWNER/imu-api:stable -f docker/prod/api/Dockerfile .
          docker push $REGISTRY/$IMAGE_OWNER/imu-api:${{ steps.meta.outputs.tag }}
          docker push $REGISTRY/$IMAGE_OWNER/imu-api:stable

      - name: Build WS
        run: |
          docker build -t $REGISTRY/$IMAGE_OWNER/imu-ws:${{ steps.meta.outputs.tag }} -t $REGISTRY/$IMAGE_OWNER/imu-ws:stable -f docker/prod/ws/Dockerfile .
          docker push $REGISTRY/$IMAGE_OWNER/imu-ws:${{ steps.meta.outputs.tag }}
          docker push $REGISTRY/$IMAGE_OWNER/imu-ws:stable

      - name: Build UI
        run: |
          docker build -t $REGISTRY/$IMAGE_OWNER/imu-ui:${{ steps.meta.outputs.tag }} -t $REGISTRY/$IMAGE_OWNER/imu-ui:stable -f docker/prod/ui/Dockerfile .
          docker push $REGISTRY/$IMAGE_OWNER/imu-ui:${{ steps.meta.outputs.tag }}
          docker push $REGISTRY/$IMAGE_OWNER/imu-ui:stable