name: pr-notify-slack-teams
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_run:
    workflows: [ "umbrella-e2e", "umbrella-diff", "umbrella-redcases", "kind-smoke", "umbrella-kind-smoke" ]
    types: [completed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Compose message
        id: msg
        env:
          REPO: ${{ github.repository }}
          PRNUM: ${{ github.event.pull_request.number || github.event.workflow_run.pull_requests[0].number }}
          SHA:   ${{ github.event.pull_request.head.sha || github.sha }}
          RESULT: ${{ github.event.workflow_run.conclusion || 'N/A' }}
        run: |
          TITLE="IMU: PR #${PRNUM} (${REPO}) — ${RESULT}"
          TEXT="Commit: ${SHA}\nCheck the PR for detailed statuses and dashboards."
          echo "title=${TITLE}" >> $GITHUB_OUTPUT
          echo "text=${TEXT}"   >> $GITHUB_OUTPUT

      - name: Slack notify (optional)
        if: ${{ secrets.SLACK_WEBHOOK_URL != '' }}
        run: |
          curl -s -X POST -H 'Content-type: application/json' \
            --data "$(jq -nc --arg t '${{ steps.msg.outputs.title }}' --arg d '${{ steps.msg.outputs.text }}' '{text: ($t + "\n" + $d)}')" \
            "${{ secrets.SLACK_WEBHOOK_URL }}" >/dev/null

      - name: Teams notify (optional)
        if: ${{ secrets.TEAMS_WEBHOOK_URL != '' }}
        run: |
          jq -nc --arg title '${{ steps.msg.outputs.title }}' --arg text '${{ steps.msg.outputs.text }}' '{
            "@type":"MessageCard","@context":"https://schema.org/extensions",
            "themeColor":"0076D7","summary":$title,
            "sections":[{"activityTitle":$title,"text":$text}]
          }' > /tmp/card.json
          curl -s -X POST -H "Content-Type: application/json" \
            -d @/tmp/card.json "${{ secrets.TEAMS_WEBHOOK_URL }}" >/dev/null